# CORE
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'haya14busa/dein-command.vim'

[[plugins]]
repo = 'tpope/vim-sensible'

# EYE CANDIES
[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Erichain/vim-monokai-pro'

[[plugins]]
repo = 'miyakogi/seiya.vim'
