# CODE
[[plugins]]
repo  = 'w0rp/ale'
on_ft = [
  'javascript',
  'python',
  'ansible',
  'yaml'
]

[[plugins]]
repo  = 'Shougo/deoplete.nvim'
on_i  = 1

# JS
[[plugins]]
repo  = 'pangloss/vim-javascript'
on_ft = 'javascript'

# OTHER
[[plugins]]
repo    = 'scrooloose/nerdcommenter'
on_map  = ['<Plug>NERDCommenterToggle']

[[plugins]]
repo = 'godlygeek/tabular'
on_cmd = ['Tabularize', 'Tab']
