# CORE
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'haya14busa/dein-command.vim'

[[plugins]]
repo = 'tpope/vim-sensible'

[[plugins]]
repo = 'kana/vim-arpeggio'

# EYE CANDIES
[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'junegunn/rainbow_parentheses.vim'

# TIME SAVER
[[plugins]]
repo = 'rshier/vimux'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'neoclide/vim-easygit'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'ervandew/supertab'

# SEARCH
[[plugins]]
repo = 'haya14busa/incsearch.vim'

[[plugins]]
repo = 'haya14busa/incsearch-easymotion.vim'
depends = ['incsearch.vim', 'vim-easymotion']

[[plugins]]
repo = 'haya14busa/incsearch-fuzzy.vim'
depends = ['incsearch.vim']

[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = 0

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'

# MISC
[[plugins]]
repo = 'editorconfig/editorconfig-vim'
