# CORE
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'haya14busa/dein-command.vim'

[[plugins]]
repo = 'tpope/vim-sensible'

[[plugins]]
repo = 'kana/vim-arpeggio'

# EYE CANDIES
[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Erichain/vim-monokai-pro'

[[plugins]]
repo = 'miyakogi/seiya.vim'

# TIME SAVER
[[plugins]]
repo = 'easymotion/vim-easymotion'

# SEARCH
[[plugins]]
repo = 'haya14busa/incsearch.vim'

[[plugins]]
repo = 'haya14busa/incsearch-easymotion.vim'
depends = ['incsearch.vim', 'vim-easymotion']

[[plugins]]
repo = 'haya14busa/incsearch-fuzzy.vim'
depends = ['incsearch.vim']

[[plugins]]
repo = 'osyo-manga/vim-anzu'
